### ISSUE TITLE
How to use this template for a multi contract app?

### ISSUE THREAD

**Issue by bbbbbbboc** [AbstractSDK/app-template#59]
I want to have a multiple contract app with structure like this
```
|-- contracts
    |-- contract1
    |-- contract2
|--packages
    |-- package1
```

I see the carrot saving repo has this structure, how is that repo instantiated?

**Comment by Buckram123** [comment]
Hey, to setup workspace from this repo all you need to do is 4 really small steps:
1. Create `contracts` directory and `app-name` inside it
2. Move `examples/`, `src/` `tests/` and `Cargo.toml` inside
3. In `justfile` rename `cosmwasm/rust-optimizer` to `cosmwasm/workspace-optimizer`
4. Create Cargo.toml in the root of the project with
```toml
[workspace]
members = ["contracts/*"]
resolver = "2"

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
```
1 commit example: 44cd2bf

**Comment by adairrr** [comment]
@bbbbbbboc we've also just released a new version of the template that is a workspace. You can choose to do it with packages as well: https://github.com/AbstractSDK/app-template/releases/tag/v0.22.0-rc.1

**Comment by bbbbbbboc** [comment]
thanks guys, i'm already using the latest version that supports multi contracts!
